In [49]:
from sklearn.naive_bayes import GaussianNB
import numpy as np
from sklearn.datasets import load_iris
from sklearn import metrics

In [50]:
iris = load_iris()

In [51]:
model = GaussianNB()

In [52]:
model.fit(iris.data, iris.target)

GaussianNB(priors=None)

In [53]:
expected = iris.target
predicted = model.predict(iris.data)
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       0.94      0.94      0.94        50
          2       0.94      0.94      0.94        50

avg / total       0.96      0.96      0.96       150

[[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]
